"""A script for renaming models generated by ClusPro. 10 models witch each of 20 receptor ensembles are renamed and moved to ./docking_prepack folder"""

import os
import shutil

for number in range(1,21):
    path = r'./en'+str(number)
    for x in range(10):
    	os.rename(path + '/model.000.0' + str(x) + '.pdb', path + '/en' + str(number) + 'model.000.0' + str(x) + '.pdb')
    	shutil.move(path + '/en' + str(number) + 'model.000.0' + str(x) + '.pdb', './docking_prepack')
    	